<?php

/**
 * @file
 * Module file.
 *
 * Various hook implementations.
 */

use Drupal\Component\Utility\Html;
use Drupal\Core\Access\AccessResultAllowed;
use Drupal\Core\Access\AccessResultForbidden;
use Drupal\Core\Access\AccessResultNeutral;
use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_theme().
 *
 * - Template override for menu__group_menu__cds_design_system.
 * - Template override for paragraph__cds_design_system_text_section.
 */
function cds_design_system_theme() {

  return [
    'menu__group_menu__cds_design_system' => [
      'base hook' => 'menu',
    ],
    'paragraph__cds_design_system_text_section' => [
      'base hook' => 'paragraph',
    ],
  ];
}

/**
 * Implements hook_ENTITY_TYPE_access() for hook_filter_format_access().
 *
 * Restricts the cds_ds_raw_html text format to the cds_design_system content
 * type.
 */
function cds_design_system_filter_format_access(EntityInterface $filter_format, string $op) {

  if ($filter_format->id() !== "cds_ds_raw_html" || $op !== 'use') {
    return new AccessResultNeutral();
  }

  $route        = Drupal::service('current_route_match');
  $node         = $route->getParameter('node');
  $node_type    = $route->getParameter('node_type');
  $group_plugin = $route->getParameter('plugin_id');

  $is_not_node_page = (is_null($node) && is_null($node_type));
  $is_group_ds_node_add_page = $group_plugin === 'group_node:cds_design_system';
  $is_not_group_ds_node_add_page = !$is_group_ds_node_add_page;

  if ($is_not_node_page && $is_not_group_ds_node_add_page) {
    return new AccessResultForbidden();
  }

  $node_bundle = '';
  if ($node) {
    $node_bundle = $node->bundle();
  }
  elseif ($node_type) {
    $node_bundle = $node_type->id();
  }
  elseif ($is_group_ds_node_add_page) {
    $node_bundle = 'cds_design_system';
  }

  if ($node_bundle === 'cds_design_system') {
    return new AccessResultAllowed();
  }
  else {
    return new AccessResultForbidden();
  }
}

/**
 * Implements hook_preprocess_menu() for hook_preprocess_menu__group_menu__cds_design_system().
 *
 * Insert unique Ids for the Design system menus.  Menus do not come with the Id
 * attribute.  But we need these Ids for the Bootstrap 4 hamburger menu control.
 *
 * Only applies when the group_content_menu module is available.
 *
 * @see https://getbootstrap.com/docs/4.0/components/navbar/#toggler
 */
function cds_design_system_preprocess_menu__group_menu__cds_design_system(&$variables) {

  $has_id = isset($variables['attributes']['id']);
  if ($has_id) {
    return;
  }

  $has_unknown_menu_name = empty($variables['menu_name']);
  if ($has_unknown_menu_name) {
    return;
  }

  $variables['attributes']['id'] = Html::getUniqueId($variables['menu_name']);
  $variables['attributes']['class'][] = 'menu--cds-design-system';
}

/**
 * Implements hook_theme_suggestions_hook_alter() for hook_theme_suggestions_page_alter().
 *
 * Adds template suggestion for the Design system content type.
 */
function cds_design_system_theme_suggestions_page_alter(array &$suggestions, array $vars) {

  $node = \Drupal::routeMatch()->getParameter('node');
  $is_node = $node;
  if (!$is_node) {
    return;
  }

  $is_design_system_page = ($node->bundle() === 'cds_design_system');
  if ($is_design_system_page) {
    $suggestions[] = 'page__cds_design_system';
  }
}

/**
 * Implements hook_preprocess_paragraph() for hook_preprocess_paragraph__cds_design_system_text_section().
 *
 * Adds news variables useful for preparing the heading element for a text
 * section Paragraph.
 */
function cds_design_system_preprocess_paragraph__cds_design_system_text_section(&$variables) {

  $variables['heading_text']  = '';
  $variables['heading_level'] = '';
  $variables['heading_id']    = '';

  $paragraph = $variables['paragraph'];
  if ($paragraph->get('localgov_header_text')->isEmpty()) {
    return;
  }

  $heading_text  = $paragraph->get('localgov_header_text')->value;
  $heading_level = $paragraph->get('localgov_heading_level')->value;
  $heading_id    = Html::getUniqueId($heading_text);

  $allowed_heading_levels = ['h2', 'h3', 'h4', 'h5', 'h6'];
  if (in_array($heading_level, $allowed_heading_levels)) {
    $variables['heading_text']  = $heading_text;
    $variables['heading_level'] = $heading_level ?: 'h2';
    $variables['heading_id']    = $heading_id;
  }
}

/**
 * Implements hook_preprocess_localgov_page_header_block().
 *
 * Adds the following variables:
 * - parent_root_label: Label of the root page in the active menu trail.
 */
function cds_design_system_preprocess_localgov_page_header_block(&$variables) {

  $current_node = Drupal::service('current_route_match')->getParameter('node');
  if (empty($current_node)) {
    return;
  }

  $variables['parent_root_label'] = Drupal::service('token')->replace(
    '[node:menu-link:root]',
    ['node' => $current_node],
    ['clear' => TRUE]
  );
}
